# Generated by Django 4.0.4 on 2022-05-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('emp_id', models.IntegerField(null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
